# Generated by Django 3.1.7 on 2021-04-14 21:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('item_name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='Item Name')),
                ('type', models.CharField(choices=[('ltr', 'Liters'), ('kg', 'Kilograms'), ('pcs', 'Pieces')], max_length=128, verbose_name='Type')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Quantity')),
                ('catagory_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.catagory', verbose_name='Catagory')),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
    ]
