# Generated by Django 3.1.7 on 2021-04-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20210416_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='photos/default-user-avatar.png', upload_to='User photos/', verbose_name='Photo'),
        ),
    ]
